-- MySQL Script generated by MySQL Workbench
-- Sat Nov  4 13:18:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `idclient` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birthdate` DATE NOT NULL,
  `gender` ENUM('male', 'female') NOT NULL,
  PRIMARY KEY (`idclient`),
  UNIQUE INDEX `idclient_UNIQUE` (`idclient` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`form` (
  `idform` INT NOT NULL,
  `credit` INT NOT NULL,
  `age` INT(3) NOT NULL,
  `income` INT NOT NULL,
  PRIMARY KEY (`idform`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`partner` (
  `idpartner` INT NOT NULL,
  PRIMARY KEY (`idpartner`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`blacklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`blacklist` (
  `idblacklist` INT NOT NULL,
  PRIMARY KEY (`idblacklist`),
  UNIQUE INDEX `idblacklist_UNIQUE` (`idblacklist` ASC),
  CONSTRAINT `client_id`
    FOREIGN KEY (`idblacklist`)
    REFERENCES `mydb`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`credit_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`credit_request` (
  `idrequest` INT NOT NULL,
  `partner` INT NOT NULL,
  `decision` ENUM('Y', 'N') NOT NULL,
  `client` INT NOT NULL,
  `status` ENUM('created', 'waiting', 'finished') NOT NULL DEFAULT 'created',
  `rejection_reason` ENUM('A', 'B') NULL,
  `date` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`idrequest`),
  INDEX `partner_idx` (`partner` ASC),
  INDEX `client_idx` (`client` ASC),
  CONSTRAINT `partner_fk`
    FOREIGN KEY (`partner`)
    REFERENCES `mydb`.`partner` (`idpartner`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `form_fk`
    FOREIGN KEY (`idrequest`)
    REFERENCES `mydb`.`form` (`idform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `client_fk`
    FOREIGN KEY (`client`)
    REFERENCES `mydb`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
